### ISSUE TITLE
About comparison method ''GRIP''

### ISSUE THREAD

**Issue by LiuYouliang** [rohanchandra30/Spectral-Trajectory-and-Behavior-Prediction#10]
1. The "GRIP" model's paper has 10 conv layers but in comparison_method/GRIP only has 5 conv layers.
2. Your comparison_method/GRIP can predict only one vehicle or all the vehicles? How to realize the "GRIP" model can predict all the vehicles as paper?

**Comment by rohanchandra30** [comment]
We referred to Figure 1 of the official [GRIP paper](https://arxiv.org/pdf/1907.07792.pdf), attached for convenience below. As you can see, there are **5** conv2D layers and **5** graph layers

![image](https://user-images.githubusercontent.com/15805136/72488523-29e89600-384c-11ea-8f8f-dcec0da48e4a.png)

**Comment by leeinscky** [comment]
Hi, when I ran the following file: TraPhic / comparison_method / GRIP / main.py, I changed the original statement in line 9: TRAIN = False to TRAIN = True, and then trained the GRIP model. But I always got the following error, the compe

(sc-glstm) zi@GRIP $ python main.py
data finished for training...
start training...
# 0/5 epoch 0/40 batch
0/128
5/128
10/128
15/128
20/128
25/128
30/128
35/128
40/128
45/128
50/128
55/128
60/128
65/128
70/128
75/128
80/128
85/128
90/128
95/128
100/128
105/128
110/128
115/128
120/128
125/128
256
256
256
256
# 0/5 epoch 1/40 batch
Traceback (most recent call last):
  File "main.py", line 39, in <module>
    encoder, decoder, grip = trainIters(epochs, tr_seq_2 , pred_seq_2, DATA, SUFIX, print_every=1, save_every=save_per_epoch)
  File "/Users/zi/bbbbbbbbbb/TraPhic/comparison_method/GRIP/def_train_eval.py", line 78, in trainIters
    grip_batch_train = load_grip_batch ( bch, train_dataloader , BATCH_SIZE )
  File "/Users/zi/bbbbbbbbbb/TraPhic/comparison_method/GRIP/def_train_eval.py", line 47, in load_grip_batch
    data[i, :, :, t] = torch.from_numpy(data_raw[i][keys[2 + t]]).to(device)
IndexError: index 128 is out of bounds for dimension 0 with size 128

I guess there is an error in the load_grip_batch(index, data_raw, batchsize) function in TraPhic/comparison_method/GRIP/def_train_eval.py. 

Thank you.

**Comment by rayguan97** [comment]
The issue should be fixed in the updated version. It's actually an indexing error. Sorry about the confusion!

**Comment by leeinscky** [comment]
Thank you for the answer, it worked well now. Here is another question about the graph_operation(self, x, adj, alpha=0.001) in TraPhic / comparison_method / GRIP / models.py.

In line 27 of models.py:  
```python
diags = torch.sum(adj, dim=1) + alpha
```
I would like to know why the value of dim is set to 1 rather than other values. I understand that this line corresponds to the following formula (6) in the paper

![image](https://user-images.githubusercontent.com/54604936/74251243-cbb5b280-4d26-11ea-8018-de3287b21a91.png)

But I am confused about the setting of the parameter dim. I would be very grateful if you could give a specific introduction.

**Comment by rohanchandra30** [comment]
The LHS is the diagonal degree matrix where the nth diagonal value in the degree matrix equals the sum of the nth row values of the adjacency matrix. This sum operation is depicted on the RHS.

The dim=1 parameter is capturing the sum operation of rows described above

**Comment by thelastpolaris** [comment]
I also have a question regarding GRIP - in models.py - line 65:
`if xt[ i ] is not None:`
You check whether xt[i] exists and then compute KNN. However, this check does no good as [0 0] is not None. Thus, you end up with the calculating distance between cars that don't exist and cars that do exist in this particular frame. Once I introduced a check for zeros computational time greatly decreased. Is my intuition correct?

**Comment by rohanchandra30** [comment]
Thanks for catching this !

Can you consider making a pull request for this so we can review and possibly include your improvements in the code. We will of course acknowledge your contributions on the main page :)

**Comment by thelastpolaris** [comment]
@rohanchandra30 could you please rerun your models? Are results consistent with the ones you have presented in your paper?

**Comment by rohanchandra30** [comment]
Yes, we didn't notice any change in the results. 

However, while we did notice some speed up, it was not by much using our pre-trained models. When you measured the speed-up, were you using our pre-trained models, or training your own? Also, how much speed up did you notice?

**Comment by thelastpolaris** [comment]
@rohanchandra30 

I was training on LYFT data with GRIP. I noticed that every epoch is 10-15 minutes (or even more) faster using stream2. This is fully expected as trajectory vectors are very sparse and you don't need to compute KNN for a lot of zeros in it.

**Comment by leeinscky** [comment]
Hi, I have a question about input data. 

In line 24-25 and line 37-38 of comparison_method/GRIP/main.py, the pre-processed data stream2 are used for GRIP model. I was wondering whether preprocessed data of stream1 such as stream1_obs_data_train.pkl could be used for the GRIP model. I tried to use stream1 data to train but the program showed that the tensor size did not match. So I guess the implementation of GRIP model only accepts stream2 data as input, right? 

Furthermore, to some extent, when your are implementing the GRIP model, the overall work principle of GRIP is similar to the stream2 channel rather than stream1 in your paper Forecasting Trajectory and Behavior of Road-Agents Using Spectral Clustering in Graph-LSTMs, right?

**Comment by rohanchandra30** [comment]
Correct - GRIP accepts Stream 2, and not Stream 1.

Could you elaborate what you mean by work principle?

**Comment by leeinscky** [comment]
Thank you for the answer, I have solved my previous confusion.

In addition, I was wondering how the following four files accepted by GRIP are generated:
stream2_obs_data_train.pkl
stream2_pred_data_train.pkl
stream2_obs_data_test.pkl
stream2_pred_data_test.pkl

Although they are already provided in resources, I am trying to run the code to regenerate these files.

**Comment by srujanpanuganti** [comment]
Hi @leeinscky , You can now see proper instructions in the data_stream.py
