### ISSUE TITLE
Question about training and test performance

### ISSUE THREAD

**Issue by richardkxu** [rohanchandra30/Spectral-Trajectory-and-Behavior-Prediction#20]
Hi, thanks for the help earlier with training the model. I was able to both test on the provided pretrained model and train my own version. However, I was not able to reach the ADE and FDE of the 2 stream model presented in the paper for any of the 3 datasets. Did I do anything wrong with the settings? Did I miss anything about training and testing? Thank you very much!

Here are my settings for testing on the pretrained model:
```
# DATA = 'APOL'
# train_seq_len = 6
# pred_seq_len = 10

# DATA = 'LYFT'
# train_seq_len = 20
# pred_seq_len = 30

DATA = 'ARGO'
train_seq_len = 20
pred_seq_len = 30

device = torch.device("cuda:0")
SUFIX = '1stS1new'
s2 = True  # if True, two stream model
TRAIN = False
EVAL = True
DIR = '../resources/data/{}/'.format(DATA)
MODEL_DIR = '../resources/trained_models/'
train_epochs = 15
save_per_epochs = 5
```

For training and testing my own version of the two stream model, I just changed `TRAIN=True` and commented out the weight loading part in line 100-104 mentioned in issue #13.

And here are the results I got:

GraphLSTM 2stream pretrained model on APOL:
```
ADE: [0.90914839 0.64782279 0.56306733 0.5403142  0.54224028 0.53483069
 0.53394937 0.5239156  0.53242273 0.52915297]
ADE: 0.5856864349124574 FDE: 0.5291529741804379
```
GraphLSTM 2stream train and eval on APOL:
```
ADE: [0.80967891 0.63155352 0.55330662 0.53059136 0.51161935 0.49851476
 0.51533204 0.51450172 0.50570612 0.51775159]
ADE: 0.558855599098217 FDE: 0.5177515886371943
```
GraphLSTM 2stream pretrained model on LYFT:
```
ADE: [1.76059701 1.5459227  1.40171521 1.29614743 1.26462214 1.21432758
 1.17958277 1.1663235  1.17910686 1.1665539  1.14079415 1.18574573
 1.14611248 1.16502993 1.16466755 1.14559825 1.17898621 1.1739172
 1.14664888 1.15151431 1.16334725 1.19269182 1.14775479 1.17731788
 1.1975847  1.18531282 1.14510642 1.18664092 1.16372672 1.17896882]
ADE: 1.2170788642297978 FDE: 1.1789688150680626
```
GraphLSTM 2stream train and eval on LYFT:
```
ADE: [2.75660344 2.87000068 3.24118411 3.27677015 3.32957331 3.49338272
 3.47019091 3.47996657 3.46567392 3.53669668 3.48731968 3.44196864
 3.53792545 3.59108491 3.50237812 3.51436095 3.53250092 3.5150889
 3.55490621 3.54828035 3.42640036 3.55179121 3.55143308 3.59700943
 3.53691211 3.47856965 3.53356165 3.5593081  3.56199221 3.47740322]
ADE: 3.4473412545880326 FDE: 3.4774032171003455
```
GraphLSTM 2stream pretrained model on ARGO:
```
ADE: [1.44311352 1.05306537 0.85268617 0.76127294 0.76007198 0.74870897
 0.77022093 0.75617026 0.73993439 0.73108752 0.74755679 0.74488927
 0.74344796 0.73345906 0.73381993 0.7427076  0.72538812 0.7611757
 0.74050142 0.74913182 0.74331341 0.74916923 0.74985219 0.74334954
 0.72703481 0.74645182 0.73885838 0.72895644 0.73708148 0.73382598]
ADE: 0.781210099374166 FDE: 0.7338259794969619
```
GraphLSTM 2stream train and eval on ARGO:
```
ADE: [1.76067697 1.82948478 1.86377637 1.88720544 1.93914945 1.91175772
 1.91425087 1.92072114 1.94933531 1.97849926 1.98920804 1.9831843
 2.00529515 1.9679096  2.02095312 1.97395443 1.96452693 1.94433968
 2.00958728 2.05102154 2.00934809 1.98193662 2.02227267 2.04026716
 1.99839567 2.01205874 1.99999502 1.98913486 1.99973676 2.01178512]
ADE: 1.964325603955906 FDE: 2.011785116844986
```

**Comment by rohanchandra30** [comment]
Hello, your approach is fine. 

The current code no longer reproduces the results in the paper due to some modifications and adjustments made to the code. For instance, see https://github.com/rohanchandra30/Spectral-Trajectory-and-Behavior-Prediction/pull/17. There were some other modifications as well.

Consequently, we are expecting to update the paper with new results. Things have become a little delayed due to the coronavirus situation, unfortunately !

Stay safe!

**Comment by richardkxu** [comment]
I see. Thanks for the reply!

I have another question about testing: It seems like we are neither loading stream2 weights nor loading the pre-computed eigenvector pickle files during the evaluation. You also mentioned in the paper that "During test time, our approach does not require traffic-graph for trajectory prediction". 
Is there a reason why we are not using stream2 during testing? And if we are not using stream2 during testing, how is that different from stream1 model or a regular LSTM Encoder-decoder model? Thanks!

**Comment by rohanchandra30** [comment]
Correct, we do not load stream 2 weights during testing. For trajectory prediction at test time, we neither perform(require) behavior prediction nor do we regularize (because we want to evaluate the regularized model that was learned during training). Re-regularizing it during testing would have affected the results.

Therefore, since we do not perform behavior prediction or regularization, we do not load stream 2 during testing.

The quoted line just intended to mean that we do not require the graphs for behavior prediction in order to predict trajectories.

Hope this clears up the confusion !

**Comment by richardkxu** [comment]
Got you! Thank you and stay safe!
